version: "3"
services:
  engecopi_apph:
    image: tomcat:9
    container_name: engecopiAppH
    ports:
      - "8022:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
    volumes:
      - ./build/libs/homologacao.war:/usr/local/tomcat/webapps/engecopiApp.war:z
      - ./db.conf:/etc/db.conf:z
    restart: always
    networks:
      rede_eng_apph:
        ipv4_address: 172.122.1.1
networks:
  rede_eng_apph:
    ipam:
      driver: default
      config:
        - subnet: 172.122.0.0/16
